/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Richard' at '12/21/16 4:41 PM' with Gradle 2.14.1
 *
 * @author Richard, @date 12/21/16 4:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
